### ISSUE TITLE
Node.js + Express Coure

### ISSUE THREAD

**Issue by jbrw1984** [jbrw1984/pokemon-card-tracker#38]
Learn Node.js
Learn Express

**Comment by averytribbett** [comment]
Avery - 47% Done with node.js
Kobe - 30% Done with node.js

**Comment by averytribbett** [comment]
Avery - 90% Done with node.js
Kobe - 30% Done with node.js

**Comment by Kobe16** [comment]
Avery - Done with Node. 50% done with Express.js
Kobe - 50% done with Node.

**Comment by averytribbett** [comment]
Avery - Made a little bit of progress on Express course.
Kobe - Made a little bit of progress on Node course.

**Comment by Kobe16** [comment]
Avery - completed Express course. Will start Mongo course
Kobe - ~75% done with Node

**Comment by averytribbett** [comment]
Kobe - Finished Node working through express
