### ISSUE TITLE
MongoDB Course

### ISSUE THREAD

**Issue by jbrw1984** [jbrw1984/pokemon-card-tracker#5]

**Comment by jbrw1984** [comment]
Just getting started on this course.

**Comment by jbrw1984** [comment]
Now, 20% done. It's only been discussing the difference between different types of DBs.

**Comment by averytribbett** [comment]
Roughly 25% done, paused for now until we move onto the backend.

**Comment by averytribbett** [comment]
Avery - Finished up the course.
